//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JHSchool.Properties {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JHSchool.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Byte[] 的當地語系化資源。
        /// </summary>
        internal static byte[] Aspose_Total {
            get {
                object obj = ResourceManager.GetObject("Aspose_Total", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap calc_save_64 {
            get {
                object obj = ResourceManager.GetObject("calc_save_64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap ClassIcon {
            get {
                object obj = ResourceManager.GetObject("ClassIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap CourseIcon {
            get {
                object obj = ResourceManager.GetObject("CourseIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap demographic_reload_64 {
            get {
                object obj = ResourceManager.GetObject("demographic_reload_64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap Export_Image {
            get {
                object obj = ResourceManager.GetObject("Export_Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap foreign_key_lock_64 {
            get {
                object obj = ResourceManager.GetObject("foreign_key_lock_64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap graduated_write_64 {
            get {
                object obj = ResourceManager.GetObject("graduated_write_64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap Import_Image {
            get {
                object obj = ResourceManager.GetObject("Import_Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 &lt;FieldDescription&gt;
        ///  &lt;Field InternalName=&quot;ClassID&quot; Name=&quot;班級系統編號&quot; PrimaryKey=&quot;True&quot; UniqueGroup=&quot;PrimaryKey&quot;/&gt;
        ///  &lt;Field InsertRequired=&quot;True&quot; InternalName=&quot;ClassName&quot; Name=&quot;班級名稱&quot; ShiftCheckable=&quot;True&quot; UniqueGroup=&quot;ClassName&quot;/&gt;
        ///  &lt;Field InsertRequired=&quot;True&quot; InternalName=&quot;TeacherName&quot; Name=&quot;班導師&quot; ShiftCheckable=&quot;True&quot;/&gt;
        ///  &lt;Field InternalName=&quot;GradeYear&quot; Name=&quot;年級&quot; ShiftCheckable=&quot;True&quot;/&gt;
        ///  &lt;!--&lt;Field InternalName=&quot;DepartmentName&quot; Name=&quot;科別&quot; ShiftCheckable=&quot;True&quot; /&gt;--&gt;
        ///  &lt;Field InternalName=&quot;GraduationPlan&quot; [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string JH_C_BulkDescription {
            get {
                return ResourceManager.GetString("JH_C_BulkDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 &lt;FieldDescription&gt;
        ///	&lt;Field DataType=&quot;integer&quot; DisplayText=&quot;班級系統編號&quot; Identifiable=&quot;True&quot; Name=&quot;ID&quot; ReadOnly=&quot;True&quot;/&gt;
        ///	&lt;Field DisplayText=&quot;班級名稱&quot; Name=&quot;ClassName&quot; ShiftCheckable=&quot;True&quot;/&gt;
        ///	&lt;Field DisplayText=&quot;班導師&quot; Name=&quot;TeacherName&quot; ShiftCheckable=&quot;True&quot;/&gt;
        ///	&lt;Field DataType=&quot;integer&quot; DisplayText=&quot;年級&quot; Name=&quot;GradeYear&quot; ShiftCheckable=&quot;True&quot;/&gt;
        ///	&lt;Field DisplayText=&quot;課程規劃&quot; Name=&quot;GraduationPlan&quot; ShiftCheckable=&quot;True&quot;/&gt;
        ///	&lt;Field DisplayText=&quot;計算規則&quot; Name=&quot;CalcuationRule&quot; ShiftCheckable=&quot;True&quot;/&gt;
        ///	&lt;Field DataType=&quot;inte [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string JH_C_ExportDescription {
            get {
                return ResourceManager.GetString("JH_C_ExportDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 &lt;ValidateRule&gt;
        ///  &lt;FieldList&gt;
        ///    &lt;Field DataType=&quot;Integer&quot; Name=&quot;班級系統編號&quot;&gt;
        ///      &lt;Validate AutoCorrect=&quot;False&quot; Description=&quot;「班級系統編號」必須是數字。 &quot; ErrorType=&quot;Error&quot; Validator=&quot;數字最大極限&quot; When=&quot;&quot; /&gt;
        ///    &lt;/Field&gt;
        ///    &lt;Field DataType=&quot;String&quot; Name=&quot;班級名稱&quot;&gt;
        ///      &lt;Validate AutoCorrect=&quot;False&quot; Description=&quot;「班級名稱」長度必須小於10個文字。 &quot; ErrorType=&quot;Error&quot; Validator=&quot;文字10&quot; When=&quot;&quot; /&gt;
        ///    &lt;/Field&gt;
        ///    &lt;Field DataType=&quot;String&quot; Name=&quot;班導師&quot;&gt;
        ///      &lt;Validate AutoCorrect=&quot;False&quot; Description=&quot;「班導師」必須存在於系統中。 &quot; ErrorType=&quot;Error&quot; Valida [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string JH_C_ImportValidatorRule {
            get {
                return ResourceManager.GetString("JH_C_ImportValidatorRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 &lt;ValidateRule&gt;
        ///  &lt;FieldList&gt;
        ///    &lt;Field DataType=&quot;Integer&quot; Name=&quot;班級系統編號&quot;&gt;
        ///      &lt;Validate AutoCorrect=&quot;False&quot; Description=&quot;「班級系統編號」必須是數字。 &quot; ErrorType=&quot;Error&quot; Validator=&quot;數字最大極限&quot; When=&quot;&quot; /&gt;
        ///    &lt;/Field&gt;
        ///    &lt;Field DataType=&quot;String&quot; Name=&quot;班級名稱&quot;&gt;
        ///      &lt;Validate AutoCorrect=&quot;False&quot; Description=&quot;「班級名稱」長度必須小於10個文字。 &quot; ErrorType=&quot;Error&quot; Validator=&quot;文字10&quot; When=&quot;&quot; /&gt;
        ///      &lt;Validate AutoCorrect=&quot;False&quot; Description=&quot;「班級名稱」不允許空白。&quot; ErrorType=&quot;Error&quot; Validator=&quot;不可空白&quot; When=&quot;&quot;/&gt;
        ///    &lt;/Field&gt;
        ///    &lt;Field DataType=&quot;St [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string JH_C_ImportValidatorRule_KH {
            get {
                return ResourceManager.GetString("JH_C_ImportValidatorRule_KH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 &lt;FieldDescription&gt;
        ///	&lt;Field DataType=&quot;integer&quot; DisplayText=&quot;課程系統編號&quot; Identifiable=&quot;True&quot; Name=&quot;ID&quot; ReadOnly=&quot;True&quot;/&gt;
        ///	&lt;Field DisplayText=&quot;課程名稱&quot; Name=&quot;CourseName&quot; ShiftCheckable=&quot;True&quot;/&gt;
        ///	&lt;Field DisplayText=&quot;科目名稱&quot; Name=&quot;Subject&quot; ShiftCheckable=&quot;True&quot;/&gt;
        ///	&lt;Field DisplayText=&quot;領域&quot; Name=&quot;Domain&quot; ShiftCheckable=&quot;True&quot;/&gt;
        ///	&lt;Field DisplayText=&quot;所屬班級&quot; Name=&quot;ClassName&quot; ShiftCheckable=&quot;True&quot;/&gt;
        ///	&lt;Field DisplayText=&quot;學年度&quot; Name=&quot;SchoolYear&quot; ShiftCheckable=&quot;True&quot;/&gt;
        ///	&lt;Field DisplayText=&quot;學期&quot; Name=&quot;Semester&quot; ShiftCheckable= [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string JH_Course_ExportDescription {
            get {
                return ResourceManager.GetString("JH_Course_ExportDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 &lt;ValidateRule&gt;
        ///  &lt;FieldList&gt;
        ///    &lt;Field DataType=&quot;Integer&quot; Name=&quot;課程系統編號&quot;&gt;
        ///      &lt;Validate AutoCorrect=&quot;False&quot; Description=&quot;「課程系統編號」必須是數字。 &quot; ErrorType=&quot;Error&quot; Validator=&quot;數字最大極限&quot; When=&quot;&quot; /&gt;
        ///    &lt;/Field&gt;
        ///    &lt;Field DataType=&quot;String&quot; Name=&quot;所屬班級&quot;&gt;
        ///      &lt;Validate AutoCorrect=&quot;False&quot; Description=&quot;「所屬班級」必須存在於系統中。 &quot; ErrorType=&quot;Error&quot; Validator=&quot;合法班級驗證&quot; When=&quot;&quot; /&gt;
        ///    &lt;/Field&gt;
        ///    &lt;Field DataType=&quot;String&quot; Name=&quot;課程名稱&quot;&gt;
        ///      &lt;Validate AutoCorrect=&quot;False&quot; Description=&quot;「課程名稱」必須有資料。 &quot; ErrorType=&quot;Error&quot; Validato [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string JH_Course_FieldValidationRule {
            get {
                return ResourceManager.GetString("JH_Course_FieldValidationRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 
        ///
        ///&lt;FieldDescription&gt;
        ///	&lt;Field InternalName=&quot;CourseID&quot; Name=&quot;課程系統編號&quot; PrimaryKey=&quot;True&quot; UniqueGroup=&quot;PrimaryKey&quot; /&gt;
        ///	&lt;Field InternalName=&quot;ClassName&quot; Name=&quot;所屬班級&quot; ShiftCheckable=&quot;True&quot; /&gt;
        ///	&lt;Field InsertRequired=&quot;True&quot; InternalName=&quot;CourseName&quot; Name=&quot;課程名稱&quot; ShiftCheckable=&quot;True&quot; UniqueGroup=&quot;SemesterUnique&quot; /&gt;
        ///	&lt;Field InternalName=&quot;SubjectName&quot; Name=&quot;科目名稱&quot; ShiftCheckable=&quot;True&quot; /&gt;
        ///	&lt;Field InternalName=&quot;Domain&quot; Name=&quot;領域&quot; ShiftCheckable=&quot;True&quot; /&gt;
        ///	&lt;!--&lt;Field InternalName=&quot;SubjectLevel&quot; Name=&quot;科目級別&quot; ShiftCheck [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string JH_Course_ImportFieldList {
            get {
                return ResourceManager.GetString("JH_Course_ImportFieldList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 &lt;FieldDescription&gt;
        ///  &lt;Field DisplayText=&quot;學生系統編號&quot; Identifiable=&quot;True&quot; Name=&quot;StudentID&quot; ReadOnly=&quot;True&quot;/&gt;
        ///  &lt;Field DisplayText=&quot;姓名&quot; Name=&quot;Name&quot; Required=&quot;True&quot; ShiftCheckable=&quot;True&quot;/&gt;
        ///  &lt;Field DisplayText=&quot;學號&quot; Identifiable=&quot;True&quot; Name=&quot;StudentNumber&quot; ShiftCheckable=&quot;True&quot;/&gt;
        ///  &lt;Field DisplayText=&quot;身分證號&quot; Identifiable=&quot;True&quot; Name=&quot;IDNumber&quot; ShiftCheckable=&quot;True&quot;/&gt;
        ///  &lt;Field DisplayText=&quot;國籍&quot; Name=&quot;Nationality&quot; ShiftCheckable=&quot;True&quot;/&gt;
        ///  &lt;Field DisplayText=&quot;出生地&quot; Name=&quot;BirthPlace&quot; ShiftCheckable=&quot;True&quot;/&gt;
        ///  &lt;Fie [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string JH_S_BulkDescription {
            get {
                return ResourceManager.GetString("JH_S_BulkDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 &lt;FieldDescription&gt;
        ///  &lt;Field DataType=&quot;integer&quot; DisplayText=&quot;學生系統編號&quot; Identifiable=&quot;True&quot; Name=&quot;StudentID&quot; ReadOnly=&quot;True&quot;/&gt;
        ///  &lt;Field DisplayText=&quot;姓名&quot; Name=&quot;Name&quot; ShiftCheckable=&quot;True&quot;/&gt;
        ///  &lt;Field DisplayText=&quot;學號&quot; Identifiable=&quot;True&quot; Name=&quot;StudentNumber&quot; ShiftCheckable=&quot;True&quot;/&gt;
        ///  &lt;Field DisplayText=&quot;身分證號&quot; Identifiable=&quot;True&quot; Name=&quot;IDNumber&quot; ShiftCheckable=&quot;True&quot;/&gt;
        ///  &lt;Field DisplayText=&quot;國籍&quot; Name=&quot;Nationality&quot; ShiftCheckable=&quot;True&quot;/&gt;
        ///  &lt;Field DisplayText=&quot;出生地&quot; Name=&quot;BirthPlace&quot; ShiftCheckable=&quot;True&quot;/&gt;
        ///  &lt; [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string JH_S_ExportDescription {
            get {
                return ResourceManager.GetString("JH_S_ExportDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 &lt;ValidateRule&gt;
        ///  &lt;FieldList&gt;
        ///    &lt;Field DataType=&quot;Integer&quot; Name=&quot;學生系統編號&quot;&gt;
        ///      &lt;Validate AutoCorrect=&quot;False&quot; Description=&quot;此欄位的資料不可重覆。 &quot; ErrorType=&quot;Error&quot; Validator=&quot;Uniq&quot; When=&quot;&quot;/&gt;
        ///    &lt;/Field&gt;
        ///    &lt;Field DataType=&quot;String&quot; Name=&quot;姓名&quot;&gt;
        ///      &lt;Validate AutoCorrect=&quot;False&quot; Description=&quot;「姓名」不允許空白。&quot; ErrorType=&quot;Error&quot; Validator=&quot;不可空白&quot; When=&quot;&quot;/&gt;
        ///      &lt;Validate AutoCorrect=&quot;False&quot; Description=&quot;「姓名」長度必須小於100個文字。&quot; ErrorType=&quot;Error&quot; Validator=&quot;文字100&quot; When=&quot;&quot;/&gt;
        ///    &lt;/Field&gt;
        ///    &lt;Field DataType=&quot;String&quot; Name=&quot; [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string JH_S_FieldValidationRule {
            get {
                return ResourceManager.GetString("JH_S_FieldValidationRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 &lt;FieldDescription&gt;
        ///  &lt;Field DisplayText=&quot;教師系統編號&quot; Identifiable=&quot;True&quot; Name=&quot;TeacherID&quot; ReadOnly=&quot;True&quot;/&gt;
        ///  &lt;Field DisplayText=&quot;教師姓名&quot; Name=&quot;Name&quot; ShiftCheckable=&quot;True&quot;/&gt;
        ///  &lt;Field DisplayText=&quot;暱稱&quot; Name=&quot;Nickname&quot; ShiftCheckable=&quot;True&quot;/&gt;
        ///  &lt;Field DisplayText=&quot;性別&quot; Name=&quot;Gender&quot;/&gt;
        ///  &lt;Field DisplayText=&quot;身分證號&quot; Identifiable=&quot;False&quot; Name=&quot;IDNumber&quot; ShiftCheckable=&quot;True&quot;/&gt;
        ///  &lt;Field DisplayText=&quot;聯絡電話&quot; Name=&quot;ContactPhone&quot; ShiftCheckable=&quot;True&quot;/&gt;
        ///  &lt;Field DisplayText=&quot;電子信箱&quot; Name=&quot;Email&quot; ShiftCheckable=&quot;True&quot;/&gt;
        ///   [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string JH_T_BulkDescription {
            get {
                return ResourceManager.GetString("JH_T_BulkDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 &lt;FieldDescription&gt;
        ///  &lt;Field DisplayText=&quot;教師系統編號&quot; Name=&quot;TeacherID&quot;/&gt;
        ///  &lt;Field DisplayText=&quot;教師姓名&quot; Name=&quot;Name&quot;/&gt;
        ///  &lt;Field DisplayText=&quot;暱稱&quot; Name=&quot;Nickname&quot;/&gt;
        ///  &lt;Field DisplayText=&quot;性別&quot; Name=&quot;Gender&quot;/&gt;
        ///  &lt;Field DisplayText=&quot;身分證號&quot; Name=&quot;IDNumber&quot;/&gt;
        ///  &lt;Field DisplayText=&quot;聯絡電話&quot; Name=&quot;ContactPhone&quot;/&gt;
        ///  &lt;Field DisplayText=&quot;電子信箱&quot; Name=&quot;Email&quot;/&gt;
        ///  &lt;Field DisplayText=&quot;教師類別&quot; Name=&quot;Category&quot;/&gt;
        ///  &lt;Field DisplayText=&quot;登入帳號&quot; Name=&quot;SmartTeacherLoginName&quot;/&gt;
        ///  &lt;Field DisplayText=&quot;帳號類型&quot; Name=&quot;AccountType&quot;/&gt;
        ///  &lt;Field Dis [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string JH_T_ExportDescription {
            get {
                return ResourceManager.GetString("JH_T_ExportDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 &lt;ValidateRule&gt;
        ///  &lt;FieldList&gt;
        ///    &lt;Field DataType=&quot;Integer&quot; Name=&quot;教師系統編號&quot;&gt;
        ///      &lt;Validate AutoCorrect=&quot;False&quot; Description=&quot;「教師系統編號」必須是數字。 &quot; ErrorType=&quot;Error&quot; Validator=&quot;Integer極限&quot; When=&quot;&quot;/&gt;
        ///    &lt;/Field&gt;
        ///    &lt;Field DataType=&quot;String&quot; Name=&quot;教師姓名&quot;&gt;
        ///      &lt;Validate AutoCorrect=&quot;False&quot; Description=&quot;「教師姓名」不允許空白。&quot; ErrorType=&quot;Error&quot; Validator=&quot;不可空白&quot; When=&quot;&quot;/&gt;
        ///      &lt;Validate AutoCorrect=&quot;False&quot; Description=&quot;「教師姓名」長度必須小於100個文字。&quot; ErrorType=&quot;Error&quot; Validator=&quot;文字100&quot; When=&quot;&quot;/&gt;
        ///    &lt;/Field&gt;
        ///    &lt;Field DataType=&quot; [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string JH_T_FieldValidationRule {
            get {
                return ResourceManager.GetString("JH_T_FieldValidationRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 &lt;FieldDescription&gt;
        ///  &lt;Field InternalName=&quot;TeacherID&quot; Name=&quot;教師系統編號&quot; PrimaryKey=&quot;True&quot; UniqueGroup=&quot;PrimaryKey&quot;/&gt;
        ///  &lt;Field InsertRequired=&quot;True&quot; InternalName=&quot;Name&quot; Name=&quot;教師姓名&quot; ShiftCheckable=&quot;True&quot; UniqueGroup=&quot;TeacherName&quot;/&gt;
        ///  &lt;Field InsertRequired=&quot;True&quot; InternalName=&quot;Nickname&quot; Name=&quot;暱稱&quot; ShiftCheckable=&quot;True&quot; UniqueGroup=&quot;TeacherName&quot;/&gt;
        ///  &lt;Field InternalName=&quot;Gender&quot; Name=&quot;性別&quot;/&gt;
        ///  &lt;Field InternalName=&quot;IDNumber&quot; Name=&quot;身分證號&quot; ShiftCheckable=&quot;True&quot; UniqueGroup=&quot;IDNumber&quot;/&gt;
        ///  &lt;Field InternalName=&quot;ContactP [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string JH_T_ImportFieldList {
            get {
                return ResourceManager.GetString("JH_T_ImportFieldList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap Loading {
            get {
                object obj = ResourceManager.GetObject("Loading", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap paste_64 {
            get {
                object obj = ResourceManager.GetObject("paste_64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap People {
            get {
                object obj = ResourceManager.GetObject("People", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap refresh_window_64 {
            get {
                object obj = ResourceManager.GetObject("refresh_window_64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap school_fav_64 {
            get {
                object obj = ResourceManager.GetObject("school_fav_64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap StudentIcon {
            get {
                object obj = ResourceManager.GetObject("StudentIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap TeacherIcon {
            get {
                object obj = ResourceManager.GetObject("TeacherIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap user_write_64 {
            get {
                object obj = ResourceManager.GetObject("user_write_64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap world_upload_64 {
            get {
                object obj = ResourceManager.GetObject("world_upload_64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
