//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JHSchool.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JHSchool.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Aspose_Total {
            get {
                object obj = ResourceManager.GetObject("Aspose_Total", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap calc_save_64 {
            get {
                object obj = ResourceManager.GetObject("calc_save_64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ClassIcon {
            get {
                object obj = ResourceManager.GetObject("ClassIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CourseIcon {
            get {
                object obj = ResourceManager.GetObject("CourseIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap demographic_reload_64 {
            get {
                object obj = ResourceManager.GetObject("demographic_reload_64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Export_Image {
            get {
                object obj = ResourceManager.GetObject("Export_Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap foreign_key_lock_64 {
            get {
                object obj = ResourceManager.GetObject("foreign_key_lock_64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap graduated_write_64 {
            get {
                object obj = ResourceManager.GetObject("graduated_write_64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Import_Image {
            get {
                object obj = ResourceManager.GetObject("Import_Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;FieldDescription&gt;
        ///  &lt;Field InternalName=&quot;ClassID&quot; Name=&quot;班級系統編號&quot; PrimaryKey=&quot;True&quot; UniqueGroup=&quot;PrimaryKey&quot;/&gt;
        ///  &lt;Field InsertRequired=&quot;True&quot; InternalName=&quot;ClassName&quot; Name=&quot;班級名稱&quot; ShiftCheckable=&quot;True&quot; UniqueGroup=&quot;ClassName&quot;/&gt;
        ///  &lt;Field InsertRequired=&quot;True&quot; InternalName=&quot;TeacherName&quot; Name=&quot;班導師&quot; ShiftCheckable=&quot;True&quot;/&gt;
        ///  &lt;Field InternalName=&quot;GradeYear&quot; Name=&quot;年級&quot; ShiftCheckable=&quot;True&quot;/&gt;
        ///  &lt;!--&lt;Field InternalName=&quot;DepartmentName&quot; Name=&quot;科別&quot; ShiftCheckable=&quot;True&quot; /&gt;--&gt;
        ///  &lt;Field InternalName=&quot;GraduationPlan&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string JH_C_BulkDescription {
            get {
                return ResourceManager.GetString("JH_C_BulkDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;FieldDescription&gt;
        ///	&lt;Field DataType=&quot;integer&quot; DisplayText=&quot;班級系統編號&quot; Identifiable=&quot;True&quot; Name=&quot;ID&quot; ReadOnly=&quot;True&quot;/&gt;
        ///	&lt;Field DisplayText=&quot;班級名稱&quot; Name=&quot;ClassName&quot; ShiftCheckable=&quot;True&quot;/&gt;
        ///	&lt;Field DisplayText=&quot;班導師&quot; Name=&quot;TeacherName&quot; ShiftCheckable=&quot;True&quot;/&gt;
        ///	&lt;Field DataType=&quot;integer&quot; DisplayText=&quot;年級&quot; Name=&quot;GradeYear&quot; ShiftCheckable=&quot;True&quot;/&gt;
        ///	&lt;Field DisplayText=&quot;課程規劃&quot; Name=&quot;GraduationPlan&quot; ShiftCheckable=&quot;True&quot;/&gt;
        ///	&lt;Field DisplayText=&quot;計算規則&quot; Name=&quot;CalcuationRule&quot; ShiftCheckable=&quot;True&quot;/&gt;
        ///	&lt;Field DataType=&quot;inte [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string JH_C_ExportDescription {
            get {
                return ResourceManager.GetString("JH_C_ExportDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;ValidateRule&gt;
        ///  &lt;FieldList&gt;
        ///    &lt;Field DataType=&quot;Integer&quot; Name=&quot;班級系統編號&quot;&gt;
        ///      &lt;Validate AutoCorrect=&quot;False&quot; Description=&quot;「班級系統編號」必須是數字。 &quot; ErrorType=&quot;Error&quot; Validator=&quot;數字最大極限&quot; When=&quot;&quot; /&gt;
        ///    &lt;/Field&gt;
        ///    &lt;Field DataType=&quot;String&quot; Name=&quot;班級名稱&quot;&gt;
        ///      &lt;Validate AutoCorrect=&quot;False&quot; Description=&quot;「班級名稱」長度必須小於10個文字。 &quot; ErrorType=&quot;Error&quot; Validator=&quot;文字10&quot; When=&quot;&quot; /&gt;
        ///    &lt;/Field&gt;
        ///    &lt;Field DataType=&quot;String&quot; Name=&quot;班導師&quot;&gt;
        ///      &lt;Validate AutoCorrect=&quot;False&quot; Description=&quot;「班導師」必須存在於系統中。 &quot; ErrorType=&quot;Error&quot; Valida [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string JH_C_ImportValidatorRule {
            get {
                return ResourceManager.GetString("JH_C_ImportValidatorRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;ValidateRule&gt;
        ///  &lt;FieldList&gt;
        ///    &lt;Field DataType=&quot;Integer&quot; Name=&quot;班級系統編號&quot;&gt;
        ///      &lt;Validate AutoCorrect=&quot;False&quot; Description=&quot;「班級系統編號」必須是數字。 &quot; ErrorType=&quot;Error&quot; Validator=&quot;數字最大極限&quot; When=&quot;&quot; /&gt;
        ///    &lt;/Field&gt;
        ///    &lt;Field DataType=&quot;String&quot; Name=&quot;班級名稱&quot;&gt;
        ///      &lt;Validate AutoCorrect=&quot;False&quot; Description=&quot;「班級名稱」長度必須小於10個文字。 &quot; ErrorType=&quot;Error&quot; Validator=&quot;文字10&quot; When=&quot;&quot; /&gt;
        ///      &lt;Validate AutoCorrect=&quot;False&quot; Description=&quot;「班級名稱」不允許空白。&quot; ErrorType=&quot;Error&quot; Validator=&quot;不可空白&quot; When=&quot;&quot;/&gt;
        ///    &lt;/Field&gt;
        ///    &lt;Field DataType=&quot;St [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string JH_C_ImportValidatorRule_KH {
            get {
                return ResourceManager.GetString("JH_C_ImportValidatorRule_KH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;FieldDescription&gt;
        ///	&lt;Field DataType=&quot;integer&quot; DisplayText=&quot;課程系統編號&quot; Identifiable=&quot;True&quot; Name=&quot;ID&quot; ReadOnly=&quot;True&quot;/&gt;
        ///	&lt;Field DisplayText=&quot;課程名稱&quot; Name=&quot;CourseName&quot; ShiftCheckable=&quot;True&quot;/&gt;
        ///	&lt;Field DisplayText=&quot;科目名稱&quot; Name=&quot;Subject&quot; ShiftCheckable=&quot;True&quot;/&gt;
        ///	&lt;Field DisplayText=&quot;領域&quot; Name=&quot;Domain&quot; ShiftCheckable=&quot;True&quot;/&gt;
        ///	&lt;Field DisplayText=&quot;所屬班級&quot; Name=&quot;ClassName&quot; ShiftCheckable=&quot;True&quot;/&gt;
        ///	&lt;Field DisplayText=&quot;學年度&quot; Name=&quot;SchoolYear&quot; ShiftCheckable=&quot;True&quot;/&gt;
        ///	&lt;Field DisplayText=&quot;學期&quot; Name=&quot;Semester&quot; ShiftCheckable= [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string JH_Course_ExportDescription {
            get {
                return ResourceManager.GetString("JH_Course_ExportDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;ValidateRule&gt;
        ///  &lt;FieldList&gt;
        ///    &lt;Field DataType=&quot;Integer&quot; Name=&quot;課程系統編號&quot;&gt;
        ///      &lt;Validate AutoCorrect=&quot;False&quot; Description=&quot;「課程系統編號」必須是數字。 &quot; ErrorType=&quot;Error&quot; Validator=&quot;數字最大極限&quot; When=&quot;&quot; /&gt;
        ///    &lt;/Field&gt;
        ///    &lt;Field DataType=&quot;String&quot; Name=&quot;所屬班級&quot;&gt;
        ///      &lt;Validate AutoCorrect=&quot;False&quot; Description=&quot;「所屬班級」必須存在於系統中。 &quot; ErrorType=&quot;Error&quot; Validator=&quot;合法班級驗證&quot; When=&quot;&quot; /&gt;
        ///    &lt;/Field&gt;
        ///    &lt;Field DataType=&quot;String&quot; Name=&quot;課程名稱&quot;&gt;
        ///      &lt;Validate AutoCorrect=&quot;False&quot; Description=&quot;「課程名稱」必須有資料。 &quot; ErrorType=&quot;Error&quot; Validato [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string JH_Course_FieldValidationRule {
            get {
                return ResourceManager.GetString("JH_Course_FieldValidationRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///
        ///&lt;FieldDescription&gt;
        ///	&lt;Field InternalName=&quot;CourseID&quot; Name=&quot;課程系統編號&quot; PrimaryKey=&quot;True&quot; UniqueGroup=&quot;PrimaryKey&quot; /&gt;
        ///	&lt;Field InternalName=&quot;ClassName&quot; Name=&quot;所屬班級&quot; ShiftCheckable=&quot;True&quot; /&gt;
        ///	&lt;Field InsertRequired=&quot;True&quot; InternalName=&quot;CourseName&quot; Name=&quot;課程名稱&quot; ShiftCheckable=&quot;True&quot; UniqueGroup=&quot;SemesterUnique&quot; /&gt;
        ///	&lt;Field InternalName=&quot;SubjectName&quot; Name=&quot;科目名稱&quot; ShiftCheckable=&quot;True&quot; /&gt;
        ///	&lt;Field InternalName=&quot;Domain&quot; Name=&quot;領域&quot; ShiftCheckable=&quot;True&quot; /&gt;
        ///	&lt;!--&lt;Field InternalName=&quot;SubjectLevel&quot; Name=&quot;科目級別&quot; ShiftCheck [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string JH_Course_ImportFieldList {
            get {
                return ResourceManager.GetString("JH_Course_ImportFieldList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;FieldDescription&gt;
        ///  &lt;Field DisplayText=&quot;學生系統編號&quot; Identifiable=&quot;True&quot; Name=&quot;StudentID&quot; ReadOnly=&quot;True&quot;/&gt;
        ///  &lt;Field DisplayText=&quot;姓名&quot; Name=&quot;Name&quot; Required=&quot;True&quot; ShiftCheckable=&quot;True&quot;/&gt;
        ///  &lt;Field DisplayText=&quot;學號&quot; Identifiable=&quot;True&quot; Name=&quot;StudentNumber&quot; ShiftCheckable=&quot;True&quot;/&gt;
        ///  &lt;Field DisplayText=&quot;身分證號&quot; Identifiable=&quot;True&quot; Name=&quot;IDNumber&quot; ShiftCheckable=&quot;True&quot;/&gt;
        ///  &lt;Field DisplayText=&quot;國籍&quot; Name=&quot;Nationality&quot; ShiftCheckable=&quot;True&quot;/&gt;
        ///  &lt;Field DisplayText=&quot;出生地&quot; Name=&quot;BirthPlace&quot; ShiftCheckable=&quot;True&quot;/&gt;
        ///  &lt;Fie [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string JH_S_BulkDescription {
            get {
                return ResourceManager.GetString("JH_S_BulkDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;FieldDescription&gt;
        ///  &lt;Field DataType=&quot;integer&quot; DisplayText=&quot;學生系統編號&quot; Identifiable=&quot;True&quot; Name=&quot;StudentID&quot; ReadOnly=&quot;True&quot;/&gt;
        ///  &lt;Field DisplayText=&quot;姓名&quot; Name=&quot;Name&quot; ShiftCheckable=&quot;True&quot;/&gt;
        ///  &lt;Field DisplayText=&quot;學號&quot; Identifiable=&quot;True&quot; Name=&quot;StudentNumber&quot; ShiftCheckable=&quot;True&quot;/&gt;
        ///  &lt;Field DisplayText=&quot;身分證號&quot; Identifiable=&quot;True&quot; Name=&quot;IDNumber&quot; ShiftCheckable=&quot;True&quot;/&gt;
        ///  &lt;Field DisplayText=&quot;國籍&quot; Name=&quot;Nationality&quot; ShiftCheckable=&quot;True&quot;/&gt;
        ///  &lt;Field DisplayText=&quot;出生地&quot; Name=&quot;BirthPlace&quot; ShiftCheckable=&quot;True&quot;/&gt;
        ///  &lt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string JH_S_ExportDescription {
            get {
                return ResourceManager.GetString("JH_S_ExportDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;ValidateRule&gt;
        ///  &lt;FieldList&gt;
        ///    &lt;Field DataType=&quot;Integer&quot; Name=&quot;學生系統編號&quot;&gt;
        ///      &lt;Validate AutoCorrect=&quot;False&quot; Description=&quot;此欄位的資料不可重覆。 &quot; ErrorType=&quot;Error&quot; Validator=&quot;Uniq&quot; When=&quot;&quot;/&gt;
        ///    &lt;/Field&gt;
        ///    &lt;Field DataType=&quot;String&quot; Name=&quot;姓名&quot;&gt;
        ///      &lt;Validate AutoCorrect=&quot;False&quot; Description=&quot;「姓名」不允許空白。&quot; ErrorType=&quot;Error&quot; Validator=&quot;不可空白&quot; When=&quot;&quot;/&gt;
        ///      &lt;Validate AutoCorrect=&quot;False&quot; Description=&quot;「姓名」長度必須小於100個文字。&quot; ErrorType=&quot;Error&quot; Validator=&quot;文字100&quot; When=&quot;&quot;/&gt;
        ///    &lt;/Field&gt;
        ///    &lt;Field DataType=&quot;String&quot; Name=&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string JH_S_FieldValidationRule {
            get {
                return ResourceManager.GetString("JH_S_FieldValidationRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;FieldDescription&gt;
        ///  &lt;Field DisplayText=&quot;教師系統編號&quot; Identifiable=&quot;True&quot; Name=&quot;TeacherID&quot; ReadOnly=&quot;True&quot;/&gt;
        ///  &lt;Field DisplayText=&quot;教師姓名&quot; Name=&quot;Name&quot; ShiftCheckable=&quot;True&quot;/&gt;
        ///  &lt;Field DisplayText=&quot;暱稱&quot; Name=&quot;Nickname&quot; ShiftCheckable=&quot;True&quot;/&gt;
        ///  &lt;Field DisplayText=&quot;性別&quot; Name=&quot;Gender&quot;/&gt;
        ///  &lt;Field DisplayText=&quot;身分證號&quot; Identifiable=&quot;False&quot; Name=&quot;IDNumber&quot; ShiftCheckable=&quot;True&quot;/&gt;
        ///  &lt;Field DisplayText=&quot;聯絡電話&quot; Name=&quot;ContactPhone&quot; ShiftCheckable=&quot;True&quot;/&gt;
        ///  &lt;Field DisplayText=&quot;電子信箱&quot; Name=&quot;Email&quot; ShiftCheckable=&quot;True&quot;/&gt;
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string JH_T_BulkDescription {
            get {
                return ResourceManager.GetString("JH_T_BulkDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;FieldDescription&gt;
        ///  &lt;Field DisplayText=&quot;教師系統編號&quot; Name=&quot;TeacherID&quot;/&gt;
        ///  &lt;Field DisplayText=&quot;教師姓名&quot; Name=&quot;Name&quot;/&gt;
        ///  &lt;Field DisplayText=&quot;暱稱&quot; Name=&quot;Nickname&quot;/&gt;
        ///  &lt;Field DisplayText=&quot;性別&quot; Name=&quot;Gender&quot;/&gt;
        ///  &lt;Field DisplayText=&quot;身分證號&quot; Name=&quot;IDNumber&quot;/&gt;
        ///  &lt;Field DisplayText=&quot;聯絡電話&quot; Name=&quot;ContactPhone&quot;/&gt;
        ///  &lt;Field DisplayText=&quot;電子信箱&quot; Name=&quot;Email&quot;/&gt;
        ///  &lt;Field DisplayText=&quot;教師類別&quot; Name=&quot;Category&quot;/&gt;
        ///  &lt;Field DisplayText=&quot;登入帳號&quot; Name=&quot;SmartTeacherLoginName&quot;/&gt;
        ///  &lt;Field DisplayText=&quot;帳號類型&quot; Name=&quot;AccountType&quot;/&gt;
        ///  &lt;Field Dis [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string JH_T_ExportDescription {
            get {
                return ResourceManager.GetString("JH_T_ExportDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;ValidateRule&gt;
        ///  &lt;FieldList&gt;
        ///    &lt;Field DataType=&quot;Integer&quot; Name=&quot;教師系統編號&quot;&gt;
        ///      &lt;Validate AutoCorrect=&quot;False&quot; Description=&quot;「教師系統編號」必須是數字。 &quot; ErrorType=&quot;Error&quot; Validator=&quot;Integer極限&quot; When=&quot;&quot;/&gt;
        ///    &lt;/Field&gt;
        ///    &lt;Field DataType=&quot;String&quot; Name=&quot;教師姓名&quot;&gt;
        ///      &lt;Validate AutoCorrect=&quot;False&quot; Description=&quot;「教師姓名」不允許空白。&quot; ErrorType=&quot;Error&quot; Validator=&quot;不可空白&quot; When=&quot;&quot;/&gt;
        ///      &lt;Validate AutoCorrect=&quot;False&quot; Description=&quot;「教師姓名」長度必須小於100個文字。&quot; ErrorType=&quot;Error&quot; Validator=&quot;文字100&quot; When=&quot;&quot;/&gt;
        ///    &lt;/Field&gt;
        ///    &lt;Field DataType=&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string JH_T_FieldValidationRule {
            get {
                return ResourceManager.GetString("JH_T_FieldValidationRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;FieldDescription&gt;
        ///  &lt;Field InternalName=&quot;TeacherID&quot; Name=&quot;教師系統編號&quot; PrimaryKey=&quot;True&quot; UniqueGroup=&quot;PrimaryKey&quot;/&gt;
        ///  &lt;Field InsertRequired=&quot;True&quot; InternalName=&quot;Name&quot; Name=&quot;教師姓名&quot; ShiftCheckable=&quot;True&quot; UniqueGroup=&quot;TeacherName&quot;/&gt;
        ///  &lt;Field InsertRequired=&quot;True&quot; InternalName=&quot;Nickname&quot; Name=&quot;暱稱&quot; ShiftCheckable=&quot;True&quot; UniqueGroup=&quot;TeacherName&quot;/&gt;
        ///  &lt;Field InternalName=&quot;Gender&quot; Name=&quot;性別&quot;/&gt;
        ///  &lt;Field InternalName=&quot;IDNumber&quot; Name=&quot;身分證號&quot; ShiftCheckable=&quot;True&quot; UniqueGroup=&quot;IDNumber&quot;/&gt;
        ///  &lt;Field InternalName=&quot;ContactP [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string JH_T_ImportFieldList {
            get {
                return ResourceManager.GetString("JH_T_ImportFieldList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Loading {
            get {
                object obj = ResourceManager.GetObject("Loading", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap paste_64 {
            get {
                object obj = ResourceManager.GetObject("paste_64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap People {
            get {
                object obj = ResourceManager.GetObject("People", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap refresh_window_64 {
            get {
                object obj = ResourceManager.GetObject("refresh_window_64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap school_fav_64 {
            get {
                object obj = ResourceManager.GetObject("school_fav_64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap StudentIcon {
            get {
                object obj = ResourceManager.GetObject("StudentIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TeacherIcon {
            get {
                object obj = ResourceManager.GetObject("TeacherIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap user_write_64 {
            get {
                object obj = ResourceManager.GetObject("user_write_64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap world_upload_64 {
            get {
                object obj = ResourceManager.GetObject("world_upload_64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
